# Generated by Django 3.2.19 on 2024-02-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, null=True)),
                ('album_image', models.ImageField(default='AlbumsImages/default.jpg', upload_to='AlbumsImages/')),
                ('album_download_link_high', models.CharField(blank=True, max_length=350, null=True)),
                ('album_download_link_high_file', models.FileField(blank=True, null=True, upload_to='AlbumsZipHigh/')),
                ('album_download_link_medium', models.CharField(blank=True, max_length=350, null=True)),
                ('album_download_link_medium_file', models.FileField(blank=True, null=True, upload_to='AlbumsZipMedium/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('release_time', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.comment')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.comment',),
        ),
    ]
