# Generated by Django 3.2.19 on 2024-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('poster', models.ImageField(upload_to='Posters/')),
                ('albums_url', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
