# Generated by Django 3.2.19 on 2024-02-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artists',
            new_name='artist',
        ),
    ]
